package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.06 13:37:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi48 */
  @Test
  public void testRekisteroi48() {    // Jasen: 48
    Jasen aku1 = new Jasen(); 
    assertEquals("From: Jasen line: 50", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    Jasen aku2 = new Jasen(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTunnusNro(); 
    int n2 = aku2.getTunnusNro(); 
    assertEquals("From: Jasen line: 56", n2-1, n1); 
    assertEquals("From: Jasen line: 57", n1+4, n2); 
  } // Generated by ComTest END
}