package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.12.11 19:59:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi190 */
  @Test
  public void testRekisteroi190() {    // Jasen: 190
    Jasen aku1 = new Jasen(); 
    assertEquals("From: Jasen line: 192", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    Jasen aku2 = new Jasen(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTunnusNro(); 
    int n2 = aku2.getTunnusNro(); 
    assertEquals("From: Jasen line: 198", n2-1, n1); 
    assertEquals("From: Jasen line: 199", n1+1, n2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetHcp236 */
  @Test
  public void testSetHcp236() {    // Jasen: 236
    Jasen jasen = new Jasen(); 
    assertEquals("From: Jasen line: 238", null, jasen.setHcp("36.0")); 
    Jasen jasen2 = new Jasen(); 
    assertEquals("From: Jasen line: 240", null, jasen2.setHcp("10.0")); 
  } // Generated by ComTest END
}