package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.27 16:46:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi185 */
  @Test
  public void testRekisteroi185() {    // Jasen: 185
    Jasen aku1 = new Jasen(); 
    assertEquals("From: Jasen line: 187", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    Jasen aku2 = new Jasen(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTunnusNro(); 
    int n2 = aku2.getTunnusNro(); 
    assertEquals("From: Jasen line: 193", n2-1, n1); 
    assertEquals("From: Jasen line: 194", n1+1, n2); 
  } // Generated by ComTest END

}