package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.12.11 19:38:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierrosTest {
    


  // Generated by ComTest BEGIN
  /** testLaskeYhteistulos79 */
  @Test
  public void testLaskeYhteistulos79() {    // Kierros: 79
    Kierros kierros = new Kierros(); 
    kierros.setTulosEtu(35); 
    kierros.setTulosTaka(40); 
    assertEquals("From: Kierros line: 83", 75, kierros.getTulosYht()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi205 */
  @Test
  public void testRekisteroi205() {    // Kierros: 205
    Kierros kierros1 = new Kierros(); 
    assertEquals("From: Kierros line: 207", 0, kierros1.getTunnusNro()); 
    kierros1.rekisteroi(); 
    Kierros kierros2 = new Kierros(); 
    kierros2.rekisteroi(); 
    int n1 = kierros1.getTunnusNro(); 
    int n2 = kierros2.getTunnusNro(); 
    assertEquals("From: Kierros line: 213", n2-1, n1); 
    assertEquals("From: Kierros line: 214", n1+1, n2); 
  } // Generated by ComTest END
}