package kerho.test.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.test.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.27 19:31:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AllTestsTest {
}